"""add statement delivery models

Revision ID: 7f5f6ac6ba92
Revises:
Create Date: 2026-03-16 19:18:09.716919

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f5f6ac6ba92"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=True)
    op.create_index(op.f("ix_customers_id"), "customers", ["id"], unique=False)
    op.create_table(
        "account_statements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("account_number_last4", sa.String(length=4), nullable=False),
        sa.Column("statement_period_start", sa.Date(), nullable=False),
        sa.Column("statement_period_end", sa.Date(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column(
            "content_type",
            sa.String(length=100),
            server_default="application/pdf",
            nullable=False,
        ),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_statements_customer_id"),
        "account_statements",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_statements_id"), "account_statements", ["id"], unique=False
    )
    op.create_table(
        "statement_download_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statement_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_downloads", sa.Integer(), server_default="1", nullable=False),
        sa.Column("download_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"], ["account_statements.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_statement_download_links_expires_at"),
        "statement_download_links",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statement_download_links_id"),
        "statement_download_links",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statement_download_links_statement_id"),
        "statement_download_links",
        ["statement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statement_download_links_token_hash"),
        "statement_download_links",
        ["token_hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_statement_download_links_token_hash"),
        table_name="statement_download_links",
    )
    op.drop_index(
        op.f("ix_statement_download_links_statement_id"),
        table_name="statement_download_links",
    )
    op.drop_index(
        op.f("ix_statement_download_links_id"), table_name="statement_download_links"
    )
    op.drop_index(
        op.f("ix_statement_download_links_expires_at"),
        table_name="statement_download_links",
    )
    op.drop_table("statement_download_links")
    op.drop_index(op.f("ix_account_statements_id"), table_name="account_statements")
    op.drop_index(
        op.f("ix_account_statements_customer_id"), table_name="account_statements"
    )
    op.drop_table("account_statements")
    op.drop_index(op.f("ix_customers_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
